export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        console: "readonly",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
      },
    },
    rules: {
      "no-console": "off",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "prefer-const": "warn",
      "no-var": "warn",
      semi: ["error", "always"],
      quotes: ["warn", "double"],
      indent: ["warn", 2],
      "comma-dangle": ["warn", "only-multiline"],
      "no-trailing-spaces": "warn",
      "eol-last": ["warn", "always"],
    },
  },
  {
    files: ["public/**/*.js"],
    languageOptions: {
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        L: "readonly",
        EventSource: "readonly",
        fetch: "readonly",
        submitText: "writable",
        initiateFetch: "writable",
        setupEventStream: "writable",
        startEventStream: "writable",
        showErrorMessage: "writable",
        renderRoute: "writable",
        drawRoute: "writable",
      },
    },
  },
];
